# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Distance Between Cities' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Distance Between Cities

  target 'Distance Between CitiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Distance Between CitiesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

 pod 'DistanceGetter' , '~> 0.1'



end
